# Scss-Lint configuration overrides
# https://github.com/causes/scss-lint

linters:
  NestingDepth:
    max_depth: 5
  PropertySortOrder:
    order: smacss
  SelectorFormat:
    convention: hyphenated_BEM
